// playground/src/demos/vue/search-field/custom-render-function.tsx
import { Label, SearchField } from "@itsjustanks/heroui-vue";
import { defineComponent } from "vue";
export default defineComponent(() => () => <SearchField name="search" render={props => <div {...props} data-custom="foo" />}>
      <Label>Search</Label>
      <SearchField.Group>
        <SearchField.SearchIcon />
        <SearchField.Input class="w-[280px]" placeholder="Search..." />
        <SearchField.ClearButton />
      </SearchField.Group>
    </SearchField>);
export default CustomRenderFunction;

// playground/src/demos/react/textfield/custom-render-function.tsx
import {Input, Label, TextField} from "@heroui/react";

function CustomRenderFunction() {
  return (
    <TextField
      className="w-full max-w-64"
      name="email"
      render={(props) => <div {...props} data-custom="foo" />}
      type="email"
    >
      <Label>Email</Label>
      <Input placeholder="Enter your email" />
    </TextField>
  );
}

export default CustomRenderFunction;
