// playground/src/demos/react/description.tsx
import { Description, Input, Label } from '@heroui/react'

export default function DescriptionDemo() {
  return (
    <div className="flex flex-col gap-1">
      <Label htmlFor="email">Email</Label>
      <Input
        aria-describedby="email-description"
        className="w-64"
        id="email"
        placeholder="you@example.com"
        type="email"
      />
      <Description id="email-description">
        We'll never share your email with anyone else.
      </Description>
    </div>
  )
}

// playground/src/demos/vue/description.tsx
import { Description, Input, Label } from "@itsjustanks/heroui-vue";
import { defineComponent } from "vue";
export default defineComponent(() => () => <div class="flex flex-col gap-1">
      <Label htmlFor="email">Email</Label>
      <Input aria-describedby="email-description" class="w-64" id="email" placeholder="you@example.com" type="email" />
      <Description id="email-description">
        We'll never share your email with anyone else.
      </Description>
    </div>);
