// playground/src/demos/vue/progress-circle/with-label.tsx
import { Label, ProgressCircle } from "@itsjustanks/heroui-vue";
import { defineComponent } from "vue";
export default defineComponent(() => () => <div class="flex items-center gap-3">
      <ProgressCircle aria-label="Loading" value={75}>
        <ProgressCircle.Track>
          <ProgressCircle.TrackCircle />
          <ProgressCircle.FillCircle />
        </ProgressCircle.Track>
      </ProgressCircle>
      <Label>75% Complete</Label>
    </div>);
export default WithLabel;

// playground/src/demos/react/progress-circle/with-label.tsx
import {Label, ProgressCircle} from "@heroui/react";

function WithLabel() {
  return (
    <div className="flex items-center gap-3">
      <ProgressCircle aria-label="Loading" value={75}>
        <ProgressCircle.Track>
          <ProgressCircle.TrackCircle />
          <ProgressCircle.FillCircle />
        </ProgressCircle.Track>
      </ProgressCircle>
      <Label>75% Complete</Label>
    </div>
  );
}

export default WithLabel;
