// playground/src/demos/vue/textarea/on-surface.tsx
import { Surface, TextArea } from "@itsjustanks/heroui-vue";
import { defineComponent } from "vue";
export default defineComponent(() => () => <Surface class="w-full rounded-3xl p-6">
      <TextArea class="w-full min-w-[280px]" placeholder="Describe your product" variant="secondary" />
    </Surface>);
export default OnSurface;

// playground/src/demos/react/textarea/on-surface.tsx
import {Surface, TextArea} from "@heroui/react";

function OnSurface() {
  return (
    <Surface className="w-full rounded-3xl p-6">
      <TextArea
        className="w-full min-w-[280px]"
        placeholder="Describe your product"
        variant="secondary"
      />
    </Surface>
  );
}

export default OnSurface;
