// playground/src/demos/vue/color-swatch-picker/stack-layout.tsx
import { ColorSwatchPicker } from "@itsjustanks/heroui-vue";
import { defineComponent } from "vue";
const colors = ["#F43F5E", "#D946EF", "#8B5CF6", "#3B82F6", "#06B6D4", "#10B981", "#84CC16"];
export default defineComponent(() => () => <ColorSwatchPicker layout="stack">
      {colors.map(color => <ColorSwatchPicker.Item key={color} color={color}>
          <ColorSwatchPicker.Swatch />
          <ColorSwatchPicker.Indicator />
        </ColorSwatchPicker.Item>)}
    </ColorSwatchPicker>);
export default StackLayout;

// playground/src/demos/react/color-swatch-picker/stack-layout.tsx
import {ColorSwatchPicker} from "@heroui/react";

const colors = ["#F43F5E", "#D946EF", "#8B5CF6", "#3B82F6", "#06B6D4", "#10B981", "#84CC16"];

function StackLayout() {
  return (
    <ColorSwatchPicker layout="stack">
      {colors.map((color) => (
        <ColorSwatchPicker.Item key={color} color={color}>
          <ColorSwatchPicker.Swatch />
          <ColorSwatchPicker.Indicator />
        </ColorSwatchPicker.Item>
      ))}
    </ColorSwatchPicker>
  );
}

export default StackLayout;
