// playground/src/demos/react/autocomplete/multiple-select.tsx
import type {Key} from "@heroui/react";

import {
  Autocomplete,
  EmptyState,
  Label,
  ListBox,
  SearchField,
  Tag,
  TagGroup,
  useFilter,
} from "@heroui/react";
import {useState} from "react";

function MultipleSelect() {
  const [selectedKeys, setSelectedKeys] = useState<Key[]>([]);
  const {contains} = useFilter({sensitivity: "base"});

  const items = [
    {id: "california", name: "California"},
    {id: "texas", name: "Texas"},
    {id: "florida", name: "Florida"},
    {id: "new-york", name: "New York"},
    {id: "illinois", name: "Illinois"},
    {id: "pennsylvania", name: "Pennsylvania"},
  ];

  const onRemoveTags = (keys: Set<Key>) => {
    setSelectedKeys((prev) => prev.filter((key) => !keys.has(key)));
  };

  return (
    <Autocomplete
      className="w-[256px]"
      placeholder="Select states"
      selectionMode="multiple"
      value={selectedKeys}
      onChange={(keys) => setSelectedKeys(keys as Key[])}
    >
      <Label>States</Label>
      <Autocomplete.Trigger>
        <Autocomplete.Value>
          {({defaultChildren, isPlaceholder, state}) => {
            if (isPlaceholder || state.selectedItems.length === 0) {
              return defaultChildren;
            }

            const selectedItemsKeys = state.selectedItems.map((item) => item.key);

            return (
              <TagGroup size="sm" onRemove={onRemoveTags}>
                <TagGroup.List>
                  {selectedItemsKeys.map((selectedItemKey) => {
                    const item = items.find((s) => s.id === selectedItemKey);

                    if (!item) return null;

                    return (
                      <Tag key={item.id} id={item.id}>
                        {item.name}
                      </Tag>
                    );
                  })}
                </TagGroup.List>
              </TagGroup>
            );
          }}
        </Autocomplete.Value>
        <Autocomplete.ClearButton />
        <Autocomplete.Indicator />
      </Autocomplete.Trigger>
      <Autocomplete.Popover>
        <Autocomplete.Filter filter={contains}>
          <SearchField autoFocus name="search" variant="secondary">
            <SearchField.Group>
              <SearchField.SearchIcon />
              <SearchField.Input placeholder="Search..." />
              <SearchField.ClearButton />
            </SearchField.Group>
          </SearchField>
          <ListBox renderEmptyState={() => <EmptyState>No results found</EmptyState>}>
            {items.map((item) => (
              <ListBox.Item key={item.id} id={item.id} textValue={item.name}>
                {item.name}
                <ListBox.ItemIndicator />
              </ListBox.Item>
            ))}
          </ListBox>
        </Autocomplete.Filter>
      </Autocomplete.Popover>
    </Autocomplete>
  );
}

export default MultipleSelect;

// playground/src/demos/vue/autocomplete/multiple-select.tsx
import type { Key } from "@itsjustanks/heroui-vue";
import { Autocomplete, EmptyState, Label, ListBox, SearchField, Tag, TagGroup, useFilter } from "@itsjustanks/heroui-vue";
import { defineComponent, ref } from "vue";
export default defineComponent(() => {
  const selectedKeys = ref([]);
  const {
    contains
  } = useFilter({
    sensitivity: "base"
  });
  const items = [{
    id: "california",
    name: "California"
  }, {
    id: "texas",
    name: "Texas"
  }, {
    id: "florida",
    name: "Florida"
  }, {
    id: "new-york",
    name: "New York"
  }, {
    id: "illinois",
    name: "Illinois"
  }, {
    id: "pennsylvania",
    name: "Pennsylvania"
  }];
  const onRemoveTags = (keys: Set<Key>) => {
    selectedKeys.value = (prev => prev.filter(key => !keys.has(key)))(selectedKeys.value);
  };
  return () => <Autocomplete class="w-[256px]" placeholder="Select states" selectionMode="multiple" value={selectedKeys.value} onChange={keys => selectedKeys.value = keys as Key[]}>
      <Label>States</Label>
      <Autocomplete.Trigger>
        <Autocomplete.Value>
          {({
          defaultChildren,
          isPlaceholder,
          state
        }) => {
          if (isPlaceholder || state.selectedItems.length === 0) {
            return defaultChildren;
          }
          const selectedItemsKeys = state.selectedItems.map(item => item.key);
          return <TagGroup size="sm" onRemove={onRemoveTags}>
                <TagGroup.List>
                  {selectedItemsKeys.map(selectedItemKey => {
                const item = items.find(s => s.id === selectedItemKey);
                if (!item) return null;
                return <Tag key={item.id} id={item.id}>
                        {item.name}
                      </Tag>;
              })}
                </TagGroup.List>
              </TagGroup>;
        }}
        </Autocomplete.Value>
        <Autocomplete.ClearButton />
        <Autocomplete.Indicator />
      </Autocomplete.Trigger>
      <Autocomplete.Popover>
        <Autocomplete.Filter filter={contains}>
          <SearchField autoFocus name="search" variant="secondary">
            <SearchField.Group>
              <SearchField.SearchIcon />
              <SearchField.Input placeholder="Search..." />
              <SearchField.ClearButton />
            </SearchField.Group>
          </SearchField>
          <ListBox renderEmptyState={() => <EmptyState>No results found</EmptyState>}>
            {items.map(item => <ListBox.Item key={item.id} id={item.id} textValue={item.name}>
                {item.name}
                <ListBox.ItemIndicator />
              </ListBox.Item>)}
          </ListBox>
        </Autocomplete.Filter>
      </Autocomplete.Popover>
    </Autocomplete>;
});
export default MultipleSelect;
