// playground/src/demos/react/autocomplete/single-select.tsx
import type {Key} from "@heroui/react";

import {Autocomplete, EmptyState, Label, ListBox, SearchField, useFilter} from "@heroui/react";
import {useState} from "react";

export default function SingleSelect() {
  const {contains} = useFilter({sensitivity: "base"});

  const [selectedKey, setSelectedKey] = useState<Key | null>(null);

  const items = [
    {id: "cat", name: "Cat"},
    {id: "dog", name: "Dog"},
    {id: "elephant", name: "Elephant"},
    {id: "lion", name: "Lion"},
    {id: "tiger", name: "Tiger"},
    {id: "giraffe", name: "Giraffe"},
  ];

  return (
    <Autocomplete
      className="w-[256px]"
      placeholder="Select an animal"
      selectionMode="single"
      value={selectedKey}
      onChange={setSelectedKey}
    >
      <Label>Favorite Animal</Label>
      <Autocomplete.Trigger>
        <Autocomplete.Value />
        <Autocomplete.ClearButton />
        <Autocomplete.Indicator />
      </Autocomplete.Trigger>
      <Autocomplete.Popover>
        <Autocomplete.Filter filter={contains}>
          <SearchField autoFocus name="search" variant="secondary">
            <SearchField.Group>
              <SearchField.SearchIcon />
              <SearchField.Input placeholder="Search animals..." />
              <SearchField.ClearButton />
            </SearchField.Group>
          </SearchField>
          <ListBox renderEmptyState={() => <EmptyState>No results found</EmptyState>}>
            {items.map((item) => (
              <ListBox.Item key={item.id} id={item.id} textValue={item.name}>
                {item.name}
                <ListBox.ItemIndicator />
              </ListBox.Item>
            ))}
          </ListBox>
        </Autocomplete.Filter>
      </Autocomplete.Popover>
    </Autocomplete>
  );
}

// playground/src/demos/vue/autocomplete/single-select.tsx
import type { Key } from "@itsjustanks/heroui-vue";
import { Autocomplete, EmptyState, Label, ListBox, SearchField, useFilter } from "@itsjustanks/heroui-vue";
import { defineComponent, ref } from "vue";
export default defineComponent(() => {
  const {
    contains
  } = useFilter({
    sensitivity: "base"
  });
  const selectedKey = ref(null);
  const items = [{
    id: "cat",
    name: "Cat"
  }, {
    id: "dog",
    name: "Dog"
  }, {
    id: "elephant",
    name: "Elephant"
  }, {
    id: "lion",
    name: "Lion"
  }, {
    id: "tiger",
    name: "Tiger"
  }, {
    id: "giraffe",
    name: "Giraffe"
  }];
  return () => <Autocomplete class="w-[256px]" placeholder="Select an animal" selectionMode="single" value={selectedKey.value} onChange={setSelectedKey}>
      <Label>Favorite Animal</Label>
      <Autocomplete.Trigger>
        <Autocomplete.Value />
        <Autocomplete.ClearButton />
        <Autocomplete.Indicator />
      </Autocomplete.Trigger>
      <Autocomplete.Popover>
        <Autocomplete.Filter filter={contains}>
          <SearchField autoFocus name="search" variant="secondary">
            <SearchField.Group>
              <SearchField.SearchIcon />
              <SearchField.Input placeholder="Search animals..." />
              <SearchField.ClearButton />
            </SearchField.Group>
          </SearchField>
          <ListBox renderEmptyState={() => <EmptyState>No results found</EmptyState>}>
            {items.map(item => <ListBox.Item key={item.id} id={item.id} textValue={item.name}>
                {item.name}
                <ListBox.ItemIndicator />
              </ListBox.Item>)}
          </ListBox>
        </Autocomplete.Filter>
      </Autocomplete.Popover>
    </Autocomplete>;
});
