// playground/src/demos/button.vue
<script setup lang="ts">
import { Button } from '@itsjustanks/heroui-vue'
</script>

<template>
  <div class="demo-row">
    <Button>Primary</Button>
    <Button variant="secondary">Secondary</Button>
    <Button variant="tertiary">Tertiary</Button>
    <Button variant="outline">Outline</Button>
    <Button variant="ghost">Ghost</Button>
    <Button variant="danger">Danger</Button>
    <Button variant="danger-soft">Danger Soft</Button>
  </div>
</template>

// playground/src/demos/button.tsx
import { Button } from '@heroui/react'

export default function ButtonDemo() {
  return (
    <div className="demo-row">
      <Button>Primary</Button>
      <Button variant="secondary">Secondary</Button>
      <Button variant="tertiary">Tertiary</Button>
      <Button variant="outline">Outline</Button>
      <Button variant="ghost">Ghost</Button>
      <Button variant="danger">Danger</Button>
      <Button variant="danger-soft">Danger Soft</Button>
    </div>
  )
}
