// playground/src/demos/checkbox.vue
<script setup lang="ts">
import { Checkbox, CheckboxControl, CheckboxIndicator, CheckboxContent } from '@itsjustanks/heroui-vue'
</script>

<template>
  <div class="demo-col">
    <Checkbox id="terms">
      <CheckboxControl>
        <CheckboxIndicator />
      </CheckboxControl>
      <CheckboxContent>
        <label for="terms">Accept terms and conditions</label>
      </CheckboxContent>
    </Checkbox>

    <Checkbox id="marketing" default-checked>
      <CheckboxControl>
        <CheckboxIndicator />
      </CheckboxControl>
      <CheckboxContent>
        <label for="marketing">Send me marketing emails</label>
      </CheckboxContent>
    </Checkbox>

    <Checkbox id="newsletter" variant="secondary">
      <CheckboxControl>
        <CheckboxIndicator />
      </CheckboxControl>
      <CheckboxContent>
        <label for="newsletter">Subscribe to newsletter</label>
      </CheckboxContent>
    </Checkbox>

    <Checkbox id="disabled" disabled>
      <CheckboxControl>
        <CheckboxIndicator />
      </CheckboxControl>
      <CheckboxContent>
        <label for="disabled">Disabled option</label>
      </CheckboxContent>
    </Checkbox>
  </div>
</template>

// playground/src/demos/checkbox.tsx
import { Checkbox, Label } from '@heroui/react'

export default function CheckboxDemo() {
  return (
    <div className="demo-col">
      <Checkbox id="terms">
        <Checkbox.Control>
          <Checkbox.Indicator />
        </Checkbox.Control>
        <Checkbox.Content>
          <Label htmlFor="terms">Accept terms and conditions</Label>
        </Checkbox.Content>
      </Checkbox>

      <Checkbox id="marketing" defaultChecked>
        <Checkbox.Control>
          <Checkbox.Indicator />
        </Checkbox.Control>
        <Checkbox.Content>
          <Label htmlFor="marketing">Send me marketing emails</Label>
        </Checkbox.Content>
      </Checkbox>

      <Checkbox id="newsletter" variant="secondary">
        <Checkbox.Control>
          <Checkbox.Indicator />
        </Checkbox.Control>
        <Checkbox.Content>
          <Label htmlFor="newsletter">Subscribe to newsletter</Label>
        </Checkbox.Content>
      </Checkbox>

      <Checkbox id="disabled" disabled>
        <Checkbox.Control>
          <Checkbox.Indicator />
        </Checkbox.Control>
        <Checkbox.Content>
          <Label htmlFor="disabled">Disabled option</Label>
        </Checkbox.Content>
      </Checkbox>
    </div>
  )
}
