// playground/src/demos/drawer.vue
<script setup lang="ts">
import {
  Drawer,
  DrawerTrigger,
  DrawerBackdrop,
  DrawerContent,
  DrawerDialog,
  DrawerHeader,
  DrawerHeading,
  DrawerBody,
  DrawerFooter,
  Button,
} from '@itsjustanks/heroui-vue'
</script>

<template>
  <div class="demo-row">
    <Drawer>
      <DrawerTrigger as-child>
        <Button variant="secondary">Open Drawer</Button>
      </DrawerTrigger>
      <DrawerBackdrop>
        <DrawerContent placement="right">
          <DrawerDialog>
            <DrawerHeader>
              <DrawerHeading>Drawer Title</DrawerHeading>
            </DrawerHeader>
            <DrawerBody>
              <p>This is a right drawer built over reka-ui Dialog. It slides in from the side with a smooth CSS transition.</p>
            </DrawerBody>
            <DrawerFooter>
              <Button variant="secondary">Cancel</Button>
              <Button>Confirm</Button>
            </DrawerFooter>
          </DrawerDialog>
        </DrawerContent>
      </DrawerBackdrop>
    </Drawer>
  </div>
</template>

// playground/src/demos/drawer.tsx
import { Button, Drawer } from '@heroui/react'

export default function DrawerDemo() {
  return (
    <div className="demo-row">
      <Drawer>
        <Button variant="secondary">Open Drawer</Button>
        <Drawer.Backdrop>
          <Drawer.Content placement="right">
            <Drawer.Dialog>
              <Drawer.Header>
                <Drawer.Heading>Drawer Title</Drawer.Heading>
              </Drawer.Header>
              <Drawer.Body>
                <p>
                  This is a right drawer built with React Aria's Modal component. It slides in
                  from the side with a smooth CSS transition.
                </p>
              </Drawer.Body>
              <Drawer.Footer>
                <Button slot="close" variant="secondary">
                  Cancel
                </Button>
                <Button slot="close">Confirm</Button>
              </Drawer.Footer>
            </Drawer.Dialog>
          </Drawer.Content>
        </Drawer.Backdrop>
      </Drawer>
    </div>
  )
}
