// playground/src/demos/vue/dropdown.tsx
import { Button, Dropdown, Label } from "@itsjustanks/heroui-vue";

/** Dropdown demo — React, HeroUI v3. */
import { defineComponent } from "vue";
export default defineComponent(() => () => <div class="demo-row">
      <Dropdown>
        <Button aria-label="Menu" variant="secondary">
          Actions
        </Button>
        <Dropdown.Popover>
          <Dropdown.Menu onAction={key => console.log(`Selected: ${key}`)}>
            <Dropdown.Item id="new-file" textValue="New file">
              <Label>New file</Label>
            </Dropdown.Item>
            <Dropdown.Item id="copy-link" textValue="Copy link">
              <Label>Copy link</Label>
            </Dropdown.Item>
            <Dropdown.Item id="edit-file" textValue="Edit file">
              <Label>Edit file</Label>
            </Dropdown.Item>
            <Dropdown.Item id="delete-file" textValue="Delete file" variant="danger">
              <Label>Delete file</Label>
            </Dropdown.Item>
          </Dropdown.Menu>
        </Dropdown.Popover>
      </Dropdown>
    </div>);

// playground/src/demos/dropdown.tsx
import { Button, Dropdown } from '@heroui/react'

export default function DropdownDemo() {
  return (
    <div className="demo-row">
      <Dropdown>
        <Button variant="secondary">Actions</Button>
        <Dropdown.Popover>
          <Dropdown.Menu>
            <Dropdown.Item id="new-file">New file</Dropdown.Item>
            <Dropdown.Item id="copy-link">Copy link</Dropdown.Item>
            <Dropdown.Item id="edit-file">Edit file</Dropdown.Item>
            <Dropdown.Item id="delete-file" variant="danger">
              Delete file
            </Dropdown.Item>
          </Dropdown.Menu>
        </Dropdown.Popover>
      </Dropdown>
    </div>
  )
}
