// playground/src/demos/kbd.tsx
import { Kbd } from '@heroui/react'

export default function KbdDemo() {
  return (
    <div className="demo-col">
      <div className="demo-row">
        <Kbd>
          <Kbd.Abbr keyValue="command" />
          <Kbd.Content>K</Kbd.Content>
        </Kbd>
        <Kbd>
          <Kbd.Abbr keyValue="shift" />
          <Kbd.Content>P</Kbd.Content>
        </Kbd>
        <Kbd>
          <Kbd.Abbr keyValue="ctrl" />
          <Kbd.Content>C</Kbd.Content>
        </Kbd>
        <Kbd>
          <Kbd.Abbr keyValue="option" />
          <Kbd.Content>D</Kbd.Content>
        </Kbd>
      </div>
      <div className="demo-row">
        <Kbd variant="light">
          <Kbd.Abbr keyValue="command" />
          <Kbd.Content>K</Kbd.Content>
        </Kbd>
        <Kbd variant="light">
          <Kbd.Abbr keyValue="shift" />
          <Kbd.Content>P</Kbd.Content>
        </Kbd>
        <Kbd variant="light">
          <Kbd.Abbr keyValue="ctrl" />
          <Kbd.Content>C</Kbd.Content>
        </Kbd>
        <Kbd variant="light">
          <Kbd.Abbr keyValue="option" />
          <Kbd.Content>D</Kbd.Content>
        </Kbd>
      </div>
    </div>
  )
}

// playground/src/demos/kbd.vue
<script setup lang="ts">
import { Kbd, KbdAbbr, KbdContent } from '@itsjustanks/heroui-vue'
</script>

<template>
  <div class="demo-col">
    <div class="demo-row">
      <Kbd>
        <KbdAbbr key-value="command" />
        <KbdContent>K</KbdContent>
      </Kbd>
      <Kbd>
        <KbdAbbr key-value="shift" />
        <KbdContent>P</KbdContent>
      </Kbd>
      <Kbd>
        <KbdAbbr key-value="ctrl" />
        <KbdContent>C</KbdContent>
      </Kbd>
      <Kbd>
        <KbdAbbr key-value="option" />
        <KbdContent>D</KbdContent>
      </Kbd>
    </div>
    <div class="demo-row">
      <Kbd variant="light">
        <KbdAbbr key-value="command" />
        <KbdContent>K</KbdContent>
      </Kbd>
      <Kbd variant="light">
        <KbdAbbr key-value="shift" />
        <KbdContent>P</KbdContent>
      </Kbd>
      <Kbd variant="light">
        <KbdAbbr key-value="ctrl" />
        <KbdContent>C</KbdContent>
      </Kbd>
      <Kbd variant="light">
        <KbdAbbr key-value="option" />
        <KbdContent>D</KbdContent>
      </Kbd>
    </div>
  </div>
</template>
