// playground/src/demos/progress.tsx
import { Label, ProgressBar } from '@heroui/react'

export default function ProgressDemo() {
  return (
    <div className="demo-col" style={{ width: '280px' }}>
      <ProgressBar aria-label="Loading" className="w-full" value={60}>
        <Label>Loading</Label>
        <ProgressBar.Output />
        <ProgressBar.Track>
          <ProgressBar.Fill />
        </ProgressBar.Track>
      </ProgressBar>

      <ProgressBar aria-label="Success" className="w-full" color="success" value={80}>
        <Label>Success</Label>
        <ProgressBar.Output />
        <ProgressBar.Track>
          <ProgressBar.Fill />
        </ProgressBar.Track>
      </ProgressBar>

      <ProgressBar aria-label="Warning" className="w-full" color="warning" value={45}>
        <Label>Warning</Label>
        <ProgressBar.Output />
        <ProgressBar.Track>
          <ProgressBar.Fill />
        </ProgressBar.Track>
      </ProgressBar>

      <ProgressBar aria-label="Danger" className="w-full" color="danger" value={30}>
        <Label>Danger</Label>
        <ProgressBar.Output />
        <ProgressBar.Track>
          <ProgressBar.Fill />
        </ProgressBar.Track>
      </ProgressBar>

      <ProgressBar aria-label="Indeterminate" className="w-full" isIndeterminate>
        <Label>Indeterminate</Label>
        <ProgressBar.Track>
          <ProgressBar.Fill />
        </ProgressBar.Track>
      </ProgressBar>
    </div>
  )
}

// playground/src/demos/progress.vue
<script setup lang="ts">
import { Progress } from '@itsjustanks/heroui-vue'
</script>

<template>
  <div class="demo-col" style="width: 280px">
    <div>
      <p style="font-size: 13px; margin-bottom: 6px">Loading… 60%</p>
      <Progress :model-value="60" />
    </div>
    <div>
      <p style="font-size: 13px; margin-bottom: 6px">Success</p>
      <Progress :model-value="80" color="success" />
    </div>
    <div>
      <p style="font-size: 13px; margin-bottom: 6px">Warning</p>
      <Progress :model-value="45" color="warning" />
    </div>
    <div>
      <p style="font-size: 13px; margin-bottom: 6px">Danger</p>
      <Progress :model-value="30" color="danger" />
    </div>
    <div>
      <p style="font-size: 13px; margin-bottom: 6px">Indeterminate</p>
      <Progress :model-value="null" />
    </div>
  </div>
</template>
