// playground/src/demos/separator.tsx
import { Separator } from '@heroui/react'

export default function SeparatorDemo() {
  return (
    <div className="demo-col" style={{ maxWidth: '400px' }}>
      <div>
        <div className="text-medium font-medium">HeroUI v3 Components</div>
        <div className="text-small text-muted mt-1">
          Beautiful, fast and modern React UI library.
        </div>
      </div>
      <Separator className="my-2" />
      <div className="text-small flex h-5 items-center gap-4">
        <span>Blog</span>
        <Separator orientation="vertical" />
        <span>Docs</span>
        <Separator orientation="vertical" />
        <span>Source</span>
      </div>
      <Separator variant="secondary" className="my-2" />
      <div className="text-small text-muted">Secondary variant above</div>
      <Separator variant="tertiary" className="my-2" />
      <div className="text-small text-muted">Tertiary variant above</div>
    </div>
  )
}

// playground/src/demos/separator.vue
<script setup lang="ts">
import { Separator } from '@itsjustanks/heroui-vue'
</script>

<template>
  <div class="demo-col" style="max-width: 400px">
    <div>
      <div style="font-size: 15px; font-weight: 500">HeroUI v3 Components</div>
      <div style="font-size: 13px; margin-top: 4px; opacity: 0.6">
        Beautiful, fast and modern Vue UI library.
      </div>
    </div>
    <Separator />
    <div style="display: flex; height: 20px; align-items: center; gap: 16px; font-size: 13px">
      <span>Blog</span>
      <Separator orientation="vertical" />
      <span>Docs</span>
      <Separator orientation="vertical" />
      <span>Source</span>
    </div>
    <Separator variant="secondary" />
    <div style="font-size: 13px; opacity: 0.5">Secondary variant above</div>
    <Separator variant="tertiary" />
    <div style="font-size: 13px; opacity: 0.5">Tertiary variant above</div>
  </div>
</template>
