// playground/src/demos/skeleton.vue
<script setup lang="ts">
import { Skeleton } from '@itsjustanks/heroui-vue'
</script>

<template>
  <div class="demo-row">
    <div style="width: 250px; padding: 16px; border-radius: 8px; background: var(--color-surface-1, #fff); box-shadow: var(--shadow-panel, 0 1px 4px rgba(0,0,0,.1))">
      <Skeleton style="height: 128px; border-radius: 8px" />
      <div style="margin-top: 20px; display: flex; flex-direction: column; gap: 12px">
        <Skeleton style="height: 12px; width: 60%; border-radius: 8px" />
        <Skeleton style="height: 12px; width: 80%; border-radius: 8px" />
        <Skeleton style="height: 12px; width: 40%; border-radius: 8px" />
      </div>
    </div>

    <div style="width: 250px; padding: 16px; border-radius: 8px; background: var(--color-surface-1, #fff); box-shadow: var(--shadow-panel, 0 1px 4px rgba(0,0,0,.1))">
      <Skeleton animation-type="pulse" style="height: 128px; border-radius: 8px" />
      <div style="margin-top: 20px; display: flex; flex-direction: column; gap: 12px">
        <Skeleton animation-type="pulse" style="height: 12px; width: 60%; border-radius: 8px" />
        <Skeleton animation-type="pulse" style="height: 12px; width: 80%; border-radius: 8px" />
        <Skeleton animation-type="pulse" style="height: 12px; width: 40%; border-radius: 8px" />
      </div>
    </div>
  </div>
</template>

// playground/src/demos/skeleton.tsx
import { Skeleton } from '@heroui/react'

export default function SkeletonDemo() {
  return (
    <div className="demo-row">
      <div className="bg-surface-1 shadow-panel w-[250px] space-y-5 rounded-lg p-4">
        <Skeleton className="h-32 rounded-lg" />
        <div className="space-y-3">
          <Skeleton className="h-3 w-3/5 rounded-lg" />
          <Skeleton className="h-3 w-4/5 rounded-lg" />
          <Skeleton className="h-3 w-2/5 rounded-lg" />
        </div>
      </div>

      <div className="bg-surface-1 shadow-panel w-[250px] space-y-5 rounded-lg p-4">
        <Skeleton animationType="pulse" className="h-32 rounded-lg" />
        <div className="space-y-3">
          <Skeleton animationType="pulse" className="h-3 w-3/5 rounded-lg" />
          <Skeleton animationType="pulse" className="h-3 w-4/5 rounded-lg" />
          <Skeleton animationType="pulse" className="h-3 w-2/5 rounded-lg" />
        </div>
      </div>
    </div>
  )
}
