// playground/src/demos/slider.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Slider } from '@itsjustanks/heroui-vue'

const volume = ref([30])
const range = ref([200, 700])
</script>

<template>
  <div class="demo-col">
    <div>
      <p style="font-size: 14px; margin-bottom: 8px">Volume: {{ volume[0] }}</p>
      <Slider v-model="volume" :min="0" :max="100" :step="1" style="width: 300px" />
    </div>
    <div>
      <p style="font-size: 14px; margin-bottom: 8px">
        Price Range: ${{ range[0] }} – ${{ range[1] }}
      </p>
      <Slider v-model="range" :min="0" :max="1000" :step="50" style="width: 300px" />
    </div>
  </div>
</template>

// playground/src/demos/slider.tsx
import { Label, Slider } from '@heroui/react'

export default function SliderDemo() {
  return (
    <div className="demo-col">
      <Slider className="w-full max-w-xs" defaultValue={30}>
        <Label>Volume</Label>
        <Slider.Output />
        <Slider.Track>
          <Slider.Fill />
          <Slider.Thumb />
        </Slider.Track>
      </Slider>

      <Slider
        className="w-full max-w-xs"
        defaultValue={[200, 700]}
        formatOptions={{ currency: 'USD', style: 'currency' }}
        maxValue={1000}
        minValue={0}
        step={50}
      >
        <Label>Price Range</Label>
        <Slider.Output />
        <Slider.Track>
          {({ state }: { state: { values: number[] } }) => (
            <>
              <Slider.Fill />
              {state.values.map((_, i) => (
                <Slider.Thumb key={i} index={i} />
              ))}
            </>
          )}
        </Slider.Track>
      </Slider>
    </div>
  )
}
