// playground/src/demos/tabs.vue
<script setup lang="ts">
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@itsjustanks/heroui-vue'
</script>

<template>
  <div class="demo-col">
    <Tabs default-value="overview" style="width: 100%; max-width: 400px">
      <TabsList aria-label="Options">
        <TabsTrigger value="overview">Overview</TabsTrigger>
        <TabsTrigger value="analytics">Analytics</TabsTrigger>
        <TabsTrigger value="reports">Reports</TabsTrigger>
      </TabsList>
      <TabsContent value="overview" style="padding-top: 16px">
        <p>View your project overview and recent activity.</p>
      </TabsContent>
      <TabsContent value="analytics" style="padding-top: 16px">
        <p>Track your metrics and analyze performance data.</p>
      </TabsContent>
      <TabsContent value="reports" style="padding-top: 16px">
        <p>Generate and download detailed reports.</p>
      </TabsContent>
    </Tabs>
  </div>
</template>

// playground/src/demos/tabs.tsx
import { Tabs } from '@heroui/react'

export default function TabsDemo() {
  return (
    <div className="demo-col">
      <Tabs className="w-full max-w-md">
        <Tabs.ListContainer>
          <Tabs.List aria-label="Options">
            <Tabs.Tab id="overview">
              Overview
              <Tabs.Indicator />
            </Tabs.Tab>
            <Tabs.Tab id="analytics">
              Analytics
              <Tabs.Indicator />
            </Tabs.Tab>
            <Tabs.Tab id="reports">
              Reports
              <Tabs.Indicator />
            </Tabs.Tab>
          </Tabs.List>
        </Tabs.ListContainer>
        <Tabs.Panel className="pt-4" id="overview">
          <p>View your project overview and recent activity.</p>
        </Tabs.Panel>
        <Tabs.Panel className="pt-4" id="analytics">
          <p>Track your metrics and analyze performance data.</p>
        </Tabs.Panel>
        <Tabs.Panel className="pt-4" id="reports">
          <p>Generate and download detailed reports.</p>
        </Tabs.Panel>
      </Tabs>
    </div>
  )
}
