// playground/src/demos/tooltip.tsx
import { Button, Tooltip } from '@heroui/react'

export default function TooltipDemo() {
  return (
    <div className="demo-row">
      <Tooltip delay={300}>
        <Button variant="secondary">Hover me</Button>
        <Tooltip.Content>
          <p>This is a tooltip</p>
        </Tooltip.Content>
      </Tooltip>
    </div>
  )
}

// playground/src/demos/tooltip.vue
<script setup lang="ts">
import { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider, Button } from '@itsjustanks/heroui-vue'
</script>

<template>
  <div class="demo-row">
    <TooltipProvider>
      <Tooltip :delay-duration="300">
        <TooltipTrigger as-child>
          <Button variant="secondary">Hover me</Button>
        </TooltipTrigger>
        <TooltipContent>This is a tooltip</TooltipContent>
      </Tooltip>
    </TooltipProvider>
  </div>
</template>
