// playground/src/demos/vue/avatar.tsx
import { defineComponent } from 'vue'
import { Avatar } from '@itsjustanks/heroui-vue'

export default defineComponent(() => () => (
  <div class="flex items-center gap-4">
    <Avatar>
      <Avatar.Image alt="John Doe" src="https://img.heroui.chat/image/avatar?w=400&h=400&u=3" />
      <Avatar.Fallback>JD</Avatar.Fallback>
    </Avatar>
    <Avatar>
      <Avatar.Image
        alt="Blue"
        src="https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/blue.jpg"
      />
      <Avatar.Fallback>B</Avatar.Fallback>
    </Avatar>
    <Avatar>
      <Avatar.Fallback>JR</Avatar.Fallback>
    </Avatar>
  </div>
))

// playground/src/demos/react/avatar.tsx
import { Avatar } from '@heroui/react'

export default function AvatarDemo() {
  return (
    <div className="flex items-center gap-4">
      <Avatar>
        <Avatar.Image alt="John Doe" src="https://img.heroui.chat/image/avatar?w=400&h=400&u=3" />
        <Avatar.Fallback>JD</Avatar.Fallback>
      </Avatar>
      <Avatar>
        <Avatar.Image
          alt="Blue"
          src="https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/blue.jpg"
        />
        <Avatar.Fallback>B</Avatar.Fallback>
      </Avatar>
      <Avatar>
        <Avatar.Fallback>JR</Avatar.Fallback>
      </Avatar>
    </div>
  )
}
