// playground/src/demos/vue/separator.tsx
import { Separator } from "@itsjustanks/heroui-vue";
import { defineComponent } from "vue";
export default defineComponent(() => () => <div class="max-w-md">
      <div class="space-y-1">
        <h4 class="text-medium font-medium">HeroUI v3 Components</h4>
        <p class="text-small text-default-400">Beautiful, fast and modern React UI library.</p>
      </div>
      <Separator class="my-4" />
      <div class="text-small flex h-5 items-center space-x-4">
        <div>Blog</div>
        <Separator orientation="vertical" />
        <div>Docs</div>
        <Separator orientation="vertical" />
        <div>Source</div>
      </div>
    </div>);

// playground/src/demos/react/separator.tsx
import { Separator } from '@heroui/react'

export default function SeparatorDemo() {
  return (
    <div className="max-w-md">
      <div className="space-y-1">
        <h4 className="text-medium font-medium">HeroUI v3 Components</h4>
        <p className="text-small text-default-400">Beautiful, fast and modern React UI library.</p>
      </div>
      <Separator className="my-4" />
      <div className="text-small flex h-5 items-center space-x-4">
        <div>Blog</div>
        <Separator orientation="vertical" />
        <div>Docs</div>
        <Separator orientation="vertical" />
        <div>Source</div>
      </div>
    </div>
  )
}
