// playground/src/demos/react/button/loading-state.tsx
import {Paperclip} from "@gravity-ui/icons";
import {Button, Spinner} from "@heroui/react";
import React, {useState} from "react";

function LoadingState() {
  const [isLoading, setLoading] = useState(false);

  const handlePress = () => {
    setLoading(true);
    setTimeout(() => setLoading(false), 2000);
  };

  return (
    <Button isPending={isLoading} onPress={handlePress}>
      {({isPending}) => (
        <>
          {isPending ? <Spinner color="current" size="sm" /> : <Paperclip />}
          {isPending ? "Uploading..." : "Upload File"}
        </>
      )}
    </Button>
  );
}

export default LoadingState;

// playground/src/demos/vue/button/loading-state.tsx
import { Paperclip } from "../../../gravity-icons-vue";
import { Button, Spinner } from "@itsjustanks/heroui-vue";
import { defineComponent, ref } from "vue";
export default defineComponent(() => {
  const isLoading = ref(false);
  const handlePress = () => {
    isLoading.value = true;
    setTimeout(() => isLoading.value = false, 2000);
  };
  return () => <Button isPending={isLoading.value} onPress={handlePress}>
      {({
      isPending
    }) => <>
          {isPending ? <Spinner color="current" size="sm" /> : <Paperclip />}
          {isPending ? "Uploading..." : "Upload File"}
        </>}
    </Button>;
});
export default LoadingState;
