// playground/src/demos/react/table/tanstack-table.tsx
import type {SortDescriptor} from "@heroui/react";
import type {SortingState} from "@tanstack/react-table";

import {Chip, Pagination, Table, cn} from "@heroui/react";
import {Icon} from "@iconify/react";
import {
  createColumnHelper,
  flexRender,
  getCoreRowModel,
  getPaginationRowModel,
  getSortedRowModel,
  useReactTable,
} from "@tanstack/react-table";
import {useMemo, useState} from "react";

// --- Data -----------------------------------------------------------------
interface User {
  id: number;
  name: string;
  role: string;
  status: "Active" | "Inactive" | "On Leave";
  email: string;
}

const statusColorMap: Record<string, "success" | "danger" | "warning"> = {
  Active: "success",
  Inactive: "danger",
  "On Leave": "warning",
};

const users: User[] = [
  {email: "kate@acme.com", id: 1, name: "Kate Moore", role: "CEO", status: "Active"},
  {email: "john@acme.com", id: 2, name: "John Smith", role: "CTO", status: "Active"},
  {email: "sara@acme.com", id: 3, name: "Sara Johnson", role: "CMO", status: "On Leave"},
  {email: "michael@acme.com", id: 4, name: "Michael Brown", role: "CFO", status: "Active"},
  {
    email: "emily@acme.com",
    id: 5,
    name: "Emily Davis",
    role: "Product Manager",
    status: "Inactive",
  },
  {email: "davis@acme.com", id: 6, name: "Davis Wilson", role: "Lead Designer", status: "Active"},
  {
    email: "olivia@acme.com",
    id: 7,
    name: "Olivia Martinez",
    role: "Frontend Engineer",
    status: "Active",
  },
  {
    email: "james@acme.com",
    id: 8,
    name: "James Taylor",
    role: "Backend Engineer",
    status: "Active",
  },
];

// --- TanStack Column Definitions ------------------------------------------
const columnHelper = createColumnHelper<User>();

const columns = [
  columnHelper.accessor("name", {header: "Name"}),
  columnHelper.accessor("role", {header: "Role"}),
  columnHelper.accessor("status", {
    cell: (info) => (
      <Chip color={statusColorMap[info.getValue()]} size="sm" variant="soft">
        {info.getValue()}
      </Chip>
    ),
    header: "Status",
  }),
  columnHelper.accessor("email", {header: "Email"}),
];

// --- Sorting Bridge -------------------------------------------------------
// Convert TanStack SortingState → React Aria SortDescriptor
function toSortDescriptor(sorting: SortingState): SortDescriptor | undefined {
  const first = sorting[0];

  if (!first) return undefined;

  return {
    column: first.id,
    direction: first.desc ? "descending" : "ascending",
  };
}

// Convert React Aria SortDescriptor → TanStack SortingState
function toSortingState(descriptor: SortDescriptor): SortingState {
  return [{desc: descriptor.direction === "descending", id: descriptor.column as string}];
}

// --- Sort Header ----------------------------------------------------------
function SortableColumnHeader({
  children,
  sortDirection,
}: {
  children: React.ReactNode;
  sortDirection?: "ascending" | "descending";
}) {
  return (
    <span className="flex items-center justify-between">
      {children}
      {!!sortDirection && (
        <Icon
          icon="gravity-ui:chevron-up"
          className={cn(
            "size-3 transform transition-transform duration-100 ease-out",
            sortDirection === "descending" ? "rotate-180" : "",
          )}
        />
      )}
    </span>
  );
}

// --- Component ------------------------------------------------------------
const PAGE_SIZE = 4;

function TanstackTable() {
  const [sorting, setSorting] = useState<SortingState>([]);

  // eslint-disable-next-line react-hooks/incompatible-library
  const table = useReactTable({
    columns,
    data: users,
    getCoreRowModel: getCoreRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
    getSortedRowModel: getSortedRowModel(),
    initialState: {pagination: {pageSize: PAGE_SIZE}},
    onSortingChange: setSorting,
    state: {sorting},
  });

  const sortDescriptor = useMemo(() => toSortDescriptor(sorting), [sorting]);

  const {pageIndex} = table.getState().pagination;
  const pageCount = table.getPageCount();
  const pages = Array.from({length: pageCount}, (_, i) => i + 1);
  const start = pageIndex * PAGE_SIZE + 1;
  const end = Math.min((pageIndex + 1) * PAGE_SIZE, users.length);

  return (
    <Table>
      <Table.ScrollContainer>
        <Table.Content
          aria-label="TanStack Table example"
          className="min-w-[600px]"
          sortDescriptor={sortDescriptor}
          onSortChange={(d) => setSorting(toSortingState(d))}
        >
          <Table.Header>
            {table.getHeaderGroups()[0]!.headers.map((header) => (
              <Table.Column
                key={header.id}
                allowsSorting={header.column.getCanSort()}
                id={header.id}
                isRowHeader={header.id === "name"}
              >
                {({sortDirection}) => (
                  <SortableColumnHeader sortDirection={sortDirection}>
                    {flexRender(header.column.columnDef.header, header.getContext())}
                  </SortableColumnHeader>
                )}
              </Table.Column>
            ))}
          </Table.Header>
          <Table.Body>
            {table.getRowModel().rows.map((row) => (
              <Table.Row key={row.id} id={row.id}>
                {row.getVisibleCells().map((cell) => (
                  <Table.Cell key={cell.id}>
                    {flexRender(cell.column.columnDef.cell, cell.getContext())}
                  </Table.Cell>
                ))}
              </Table.Row>
            ))}
          </Table.Body>
        </Table.Content>
      </Table.ScrollContainer>
      <Table.Footer>
        <Pagination size="sm">
          <Pagination.Summary>
            {start} to {end} of {users.length} results
          </Pagination.Summary>
          <Pagination.Content>
            <Pagination.Item>
              <Pagination.Previous
                isDisabled={!table.getCanPreviousPage()}
                onPress={() => table.previousPage()}
              >
                <Pagination.PreviousIcon />
                Prev
              </Pagination.Previous>
            </Pagination.Item>
            {pages.map((p) => (
              <Pagination.Item key={p}>
                <Pagination.Link
                  isActive={p === pageIndex + 1}
                  onPress={() => table.setPageIndex(p - 1)}
                >
                  {p}
                </Pagination.Link>
              </Pagination.Item>
            ))}
            <Pagination.Item>
              <Pagination.Next
                isDisabled={!table.getCanNextPage()}
                onPress={() => table.nextPage()}
              >
                Next
                <Pagination.NextIcon />
              </Pagination.Next>
            </Pagination.Item>
          </Pagination.Content>
        </Pagination>
      </Table.Footer>
    </Table>
  );
}


export default toSortDescriptor;

// playground/src/demos/vue/table/tanstack-table.tsx
import type { SortDescriptor } from "@itsjustanks/heroui-vue";
import type { SortingState } from "@tanstack/react-table";
import { Chip, Pagination, Table, cn } from "@itsjustanks/heroui-vue";
import { Icon } from "@iconify/react";
import { createColumnHelper, flexRender, getCoreRowModel, getPaginationRowModel, getSortedRowModel, useReactTable } from "@tanstack/react-table";
import { computed, defineComponent, ref } from "vue";
// --- Data -----------------------------------------------------------------
interface User {
  id: number;
  name: string;
  role: string;
  status: "Active" | "Inactive" | "On Leave";
  email: string;
}
const statusColorMap: Record<string, "success" | "danger" | "warning"> = {
  Active: "success",
  Inactive: "danger",
  "On Leave": "warning"
};
const users: User[] = [{
  email: "kate@acme.com",
  id: 1,
  name: "Kate Moore",
  role: "CEO",
  status: "Active"
}, {
  email: "john@acme.com",
  id: 2,
  name: "John Smith",
  role: "CTO",
  status: "Active"
}, {
  email: "sara@acme.com",
  id: 3,
  name: "Sara Johnson",
  role: "CMO",
  status: "On Leave"
}, {
  email: "michael@acme.com",
  id: 4,
  name: "Michael Brown",
  role: "CFO",
  status: "Active"
}, {
  email: "emily@acme.com",
  id: 5,
  name: "Emily Davis",
  role: "Product Manager",
  status: "Inactive"
}, {
  email: "davis@acme.com",
  id: 6,
  name: "Davis Wilson",
  role: "Lead Designer",
  status: "Active"
}, {
  email: "olivia@acme.com",
  id: 7,
  name: "Olivia Martinez",
  role: "Frontend Engineer",
  status: "Active"
}, {
  email: "james@acme.com",
  id: 8,
  name: "James Taylor",
  role: "Backend Engineer",
  status: "Active"
}];

// --- TanStack Column Definitions ------------------------------------------
const columnHelper = createColumnHelper<User>();
const columns = [columnHelper.accessor("name", {
  header: "Name"
}), columnHelper.accessor("role", {
  header: "Role"
}), columnHelper.accessor("status", {
  cell: info => <Chip color={statusColorMap[info.getValue()]} size="sm" variant="soft">
        {info.getValue()}
      </Chip>,
  header: "Status"
}), columnHelper.accessor("email", {
  header: "Email"
})];

// --- Sorting Bridge -------------------------------------------------------
// Convert TanStack SortingState → React Aria SortDescriptor
function toSortDescriptor(sorting: SortingState): SortDescriptor | undefined {
  const first = sorting[0];
  if (!first) return undefined;
  return {
    column: first.id,
    direction: first.desc ? "descending" : "ascending"
  };
}

// Convert React Aria SortDescriptor → TanStack SortingState
function toSortingState(descriptor: SortDescriptor): SortingState {
  return [{
    desc: descriptor.direction === "descending",
    id: descriptor.column as string
  }];
}

// --- Sort Header ----------------------------------------------------------
function SortableColumnHeader({
  children,
  sortDirection
}: {
  children: React.ReactNode;
  sortDirection?: "ascending" | "descending";
}) {
  return <span className="flex items-center justify-between">
      {children}
      {!!sortDirection && <Icon icon="gravity-ui:chevron-up" className={cn("size-3 transform transition-transform duration-100 ease-out", sortDirection === "descending" ? "rotate-180" : "")} />}
    </span>;
}

// --- Component ------------------------------------------------------------
const PAGE_SIZE = 4;
export default defineComponent(() => {
  const sorting = ref([]);
  // eslint-disable-next-line react-hooks/incompatible-library
  const table = useReactTable({
    columns,
    data: users,
    getCoreRowModel: getCoreRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
    getSortedRowModel: getSortedRowModel(),
    initialState: {
      pagination: {
        pageSize: PAGE_SIZE
      }
    },
    onSortingChange: v => sorting.value = v,
    state: {
      sorting: sorting.value
    }
  });
  const sortDescriptor = computed(() => toSortDescriptor(sorting.value));
  const {
    pageIndex
  } = table.getState().pagination;
  const pageCount = table.getPageCount();
  const pages = Array.from({
    length: pageCount
  }, (_, i) => i + 1);
  const start = pageIndex * PAGE_SIZE + 1;
  const end = Math.min((pageIndex + 1) * PAGE_SIZE, users.length);
  return () => <Table>
      <Table.ScrollContainer>
        <Table.Content aria-label="TanStack Table example" class="min-w-[600px]" sortDescriptor={sortDescriptor.value} onSortChange={d => sorting.value = toSortingState(d)}>
          <Table.Header>
            {table.getHeaderGroups()[0]!.headers.map(header => <Table.Column key={header.id} allowsSorting={header.column.getCanSort()} id={header.id} isRowHeader={header.id === "name"}>
                {({
              sortDirection
            }) => <SortableColumnHeader sortDirection={sortDirection}>
                    {flexRender(header.column.columnDef.header, header.getContext())}
                  </SortableColumnHeader>}
              </Table.Column>)}
          </Table.Header>
          <Table.Body>
            {table.getRowModel().rows.map(row => <Table.Row key={row.id} id={row.id}>
                {row.getVisibleCells().map(cell => <Table.Cell key={cell.id}>
                    {flexRender(cell.column.columnDef.cell, cell.getContext())}
                  </Table.Cell>)}
              </Table.Row>)}
          </Table.Body>
        </Table.Content>
      </Table.ScrollContainer>
      <Table.Footer>
        <Pagination size="sm">
          <Pagination.Summary>
            {start} to {end} of {users.length} results
          </Pagination.Summary>
          <Pagination.Content>
            <Pagination.Item>
              <Pagination.Previous isDisabled={!table.getCanPreviousPage()} onPress={() => table.previousPage()}>
                <Pagination.PreviousIcon />
                Prev
              </Pagination.Previous>
            </Pagination.Item>
            {pages.map(p => <Pagination.Item key={p}>
                <Pagination.Link isActive={p === pageIndex + 1} onPress={() => table.setPageIndex(p - 1)}>
                  {p}
                </Pagination.Link>
              </Pagination.Item>)}
            <Pagination.Item>
              <Pagination.Next isDisabled={!table.getCanNextPage()} onPress={() => table.nextPage()}>
                Next
                <Pagination.NextIcon />
              </Pagination.Next>
            </Pagination.Item>
          </Pagination.Content>
        </Pagination>
      </Table.Footer>
    </Table>;
});
export default TanstackTable;
