// playground/src/demos/react/alert-dialog/statuses.tsx
import {AlertDialog, Button} from "@heroui/react";

export function Statuses() {
  const examples = [
    {
      actions: {
        cancel: "Stay Signed In",
        confirm: "Sign Out",
      },
      body: "You'll need to sign in again to access your account. Any unsaved changes will be lost.",
      classNames: "bg-accent-soft text-accent-soft-foreground",
      header: "Sign out of your account?",
      status: "accent",
      trigger: "Sign Out",
    },
    {
      actions: {
        cancel: "Not Yet",
        confirm: "Mark Complete",
      },
      body: "This will mark the task as complete and notify all team members. The task will be moved to your completed list.",
      classNames: "bg-success-soft text-success-soft-foreground",
      header: "Complete this task?",
      status: "success",
      trigger: "Complete Task",
    },
    {
      actions: {
        cancel: "Keep Editing",
        confirm: "Discard",
      },
      body: "You have unsaved changes that will be permanently lost. Are you sure you want to discard them?",
      classNames: "bg-warning-soft text-warning-soft-foreground",
      header: "Discard unsaved changes?",
      status: "warning",
      trigger: "Discard Changes",
    },
    {
      actions: {
        cancel: "Cancel",
        confirm: "Delete Account",
      },
      body: "This will permanently delete your account and remove all your data from our servers. This action is irreversible.",
      classNames: "bg-danger-soft text-danger-soft-foreground",
      header: "Delete your account?",
      status: "danger",
      trigger: "Delete Account",
    },
  ] as const;

  return (
    <div className="flex flex-wrap gap-4">
      {examples.map(({actions, body, classNames, header, status, trigger}) => (
        <AlertDialog key={status}>
          <Button className={classNames}>{trigger}</Button>
          <AlertDialog.Backdrop>
            <AlertDialog.Container>
              <AlertDialog.Dialog className="sm:max-w-[400px]">
                <AlertDialog.CloseTrigger />
                <AlertDialog.Header>
                  <AlertDialog.Icon status={status} />
                  <AlertDialog.Heading>{header}</AlertDialog.Heading>
                </AlertDialog.Header>
                <AlertDialog.Body>
                  <p>{body}</p>
                </AlertDialog.Body>
                <AlertDialog.Footer>
                  <Button slot="close" variant="tertiary">
                    {actions.cancel}
                  </Button>
                  <Button slot="close" variant={status === "danger" ? "danger" : "primary"}>
                    {actions.confirm}
                  </Button>
                </AlertDialog.Footer>
              </AlertDialog.Dialog>
            </AlertDialog.Container>
          </AlertDialog.Backdrop>
        </AlertDialog>
      ))}
    </div>
  );
}

// playground/src/demos/vue/alert-dialog/statuses.tsx
import { AlertDialog, Button } from "@itsjustanks/heroui-vue";
import { defineComponent } from "vue";
export default defineComponent(() => {
  const examples = [{
    actions: {
      cancel: "Stay Signed In",
      confirm: "Sign Out"
    },
    body: "You'll need to sign in again to access your account. Any unsaved changes will be lost.",
    classNames: "bg-accent-soft text-accent-soft-foreground",
    header: "Sign out of your account?",
    status: "accent",
    trigger: "Sign Out"
  }, {
    actions: {
      cancel: "Not Yet",
      confirm: "Mark Complete"
    },
    body: "This will mark the task as complete and notify all team members. The task will be moved to your completed list.",
    classNames: "bg-success-soft text-success-soft-foreground",
    header: "Complete this task?",
    status: "success",
    trigger: "Complete Task"
  }, {
    actions: {
      cancel: "Keep Editing",
      confirm: "Discard"
    },
    body: "You have unsaved changes that will be permanently lost. Are you sure you want to discard them?",
    classNames: "bg-warning-soft text-warning-soft-foreground",
    header: "Discard unsaved changes?",
    status: "warning",
    trigger: "Discard Changes"
  }, {
    actions: {
      cancel: "Cancel",
      confirm: "Delete Account"
    },
    body: "This will permanently delete your account and remove all your data from our servers. This action is irreversible.",
    classNames: "bg-danger-soft text-danger-soft-foreground",
    header: "Delete your account?",
    status: "danger",
    trigger: "Delete Account"
  }] as const;
  return () => <div class="flex flex-wrap gap-4">
      {examples.map(({
      actions,
      body,
      classNames,
      header,
      status,
      trigger
    }) => <AlertDialog key={status}>
          <Button class={classNames}>{trigger}</Button>
          <AlertDialog.Backdrop>
            <AlertDialog.Container>
              <AlertDialog.Dialog class="sm:max-w-[400px]">
                <AlertDialog.CloseTrigger />
                <AlertDialog.Header>
                  <AlertDialog.Icon status={status} />
                  <AlertDialog.Heading>{header}</AlertDialog.Heading>
                </AlertDialog.Header>
                <AlertDialog.Body>
                  <p>{body}</p>
                </AlertDialog.Body>
                <AlertDialog.Footer>
                  <Button slot="close" variant="tertiary">
                    {actions.cancel}
                  </Button>
                  <Button slot="close" variant={status === "danger" ? "danger" : "primary"}>
                    {actions.confirm}
                  </Button>
                </AlertDialog.Footer>
              </AlertDialog.Dialog>
            </AlertDialog.Container>
          </AlertDialog.Backdrop>
        </AlertDialog>)}
    </div>;
});
export default Statuses;
