// playground/src/demos/vue/input-group/with-badge-suffix.tsx
import { Chip, InputGroup, TextField } from "@itsjustanks/heroui-vue";
import { defineComponent } from "vue";
export default defineComponent(() => () => <TextField aria-label="Email address" class="w-full max-w-[280px]" name="email">
      <InputGroup>
        <InputGroup.Input class="w-full max-w-[280px]" placeholder="Email address" />
        <InputGroup.Suffix class="pr-2">
          <Chip color="accent" size="md" variant="soft">
            Pro
          </Chip>
        </InputGroup.Suffix>
      </InputGroup>
    </TextField>);
export default WithBadgeSuffix;

// playground/src/demos/react/input-group/with-badge-suffix.tsx
import {Chip, InputGroup, TextField} from "@heroui/react";

function WithBadgeSuffix() {
  return (
    <TextField aria-label="Email address" className="w-full max-w-[280px]" name="email">
      <InputGroup>
        <InputGroup.Input className="w-full max-w-[280px]" placeholder="Email address" />
        <InputGroup.Suffix className="pr-2">
          <Chip color="accent" size="md" variant="soft">
            Pro
          </Chip>
        </InputGroup.Suffix>
      </InputGroup>
    </TextField>
  );
}

export default WithBadgeSuffix;
