// playground/src/demos/vue/input-group/with-text-prefix.tsx
import { InputGroup, Label, TextField } from "@itsjustanks/heroui-vue";
import { defineComponent } from "vue";
export default defineComponent(() => () => <TextField class="w-full max-w-[280px]" defaultValue="heroui.com" name="website">
      <Label>Website</Label>
      <InputGroup>
        <InputGroup.Prefix>https://</InputGroup.Prefix>
        <InputGroup.Input class="w-full max-w-[280px]" />
      </InputGroup>
    </TextField>);
export default WithTextPrefix;

// playground/src/demos/react/input-group/with-text-prefix.tsx
import {InputGroup, Label, TextField} from "@heroui/react";

function WithTextPrefix() {
  return (
    <TextField className="w-full max-w-[280px]" defaultValue="heroui.com" name="website">
      <Label>Website</Label>
      <InputGroup>
        <InputGroup.Prefix>https://</InputGroup.Prefix>
        <InputGroup.Input className="w-full max-w-[280px]" />
      </InputGroup>
    </TextField>
  );
}

export default WithTextPrefix;
