// playground/src/demos/vue/input-group/with-loading-suffix.tsx
import { InputGroup, Spinner, TextField } from "@itsjustanks/heroui-vue";
import { defineComponent } from "vue";
export default defineComponent(() => () => <TextField class="w-full max-w-[280px]" defaultValue="Sending..." name="status">
      <InputGroup>
        <InputGroup.Input class="w-full max-w-[280px]" />
        <InputGroup.Suffix>
          <Spinner class="size-4" />
        </InputGroup.Suffix>
      </InputGroup>
    </TextField>);
export default WithLoadingSuffix;

// playground/src/demos/react/input-group/with-loading-suffix.tsx
import {InputGroup, Spinner, TextField} from "@heroui/react";

export function WithLoadingSuffix() {
  return (
    <TextField className="w-full max-w-[280px]" defaultValue="Sending..." name="status">
      <InputGroup>
        <InputGroup.Input className="w-full max-w-[280px]" />
        <InputGroup.Suffix>
          <Spinner className="size-4" />
        </InputGroup.Suffix>
      </InputGroup>
    </TextField>
  );
}

export default WithLoadingSuffix;
