// playground/src/demos/react/time-field/controlled.tsx
import type {TimeValue} from "@heroui/react";

import {Button, Description, Label, TimeField} from "@heroui/react";
import {Time, getLocalTimeZone, now} from "@internationalized/date";
import {useState} from "react";

function Controlled() {
  const [value, setValue] = useState<TimeValue | null>(null);

  return (
    <div className="flex flex-col gap-4">
      <TimeField className="w-[256px]" name="time" value={value} onChange={setValue}>
        <Label>Time</Label>
        <TimeField.Group>
          <TimeField.Input>{(segment) => <TimeField.Segment segment={segment} />}</TimeField.Input>
        </TimeField.Group>
        <Description>Current value: {value ? value.toString() : "(empty)"}</Description>
      </TimeField>
      <div className="flex gap-2">
        <Button
          variant="tertiary"
          onPress={() => {
            const currentTime = now(getLocalTimeZone());

            setValue(new Time(currentTime.hour, currentTime.minute, currentTime.second));
          }}
        >
          Set now
        </Button>
        <Button variant="tertiary" onPress={() => setValue(null)}>
          Clear
        </Button>
      </div>
    </div>
  );
}

export default Controlled;

// playground/src/demos/vue/date-field/controlled.tsx
import type { DateValue } from "@internationalized/date";
import { Button, DateField, Description, Label } from "@itsjustanks/heroui-vue";
import { getLocalTimeZone, today } from "@internationalized/date";
import { defineComponent, ref } from "vue";
export default defineComponent(() => {
  const value = ref(null);
  return () => <div class="flex flex-col gap-4">
      <DateField class="w-[256px]" name="date" value={value.value} onChange={v => value.value = v}>
        <Label>Date</Label>
        <DateField.Group>
          <DateField.Input>{segment => <DateField.Segment segment={segment} />}</DateField.Input>
        </DateField.Group>
        <Description>Current value: {value.value ? value.value.toString() : "(empty)"}</Description>
      </DateField>
      <div class="flex gap-2">
        <Button variant="tertiary" onPress={() => value.value = today(getLocalTimeZone())}>
          Set today
        </Button>
        <Button variant="tertiary" onPress={() => value.value = null}>
          Clear
        </Button>
      </div>
    </div>;
});
export default Controlled;
