// playground/src/demos/react/search-field/custom-render-function.tsx
import {Label, SearchField} from "@heroui/react";

function CustomRenderFunction() {
  return (
    <SearchField name="search" render={(props) => <div {...props} data-custom="foo" />}>
      <Label>Search</Label>
      <SearchField.Group>
        <SearchField.SearchIcon />
        <SearchField.Input className="w-[280px]" placeholder="Search..." />
        <SearchField.ClearButton />
      </SearchField.Group>
    </SearchField>
  );
}

export default CustomRenderFunction;

// playground/src/demos/vue/date-field/custom-render-function.tsx
import { DateField, Label } from "@itsjustanks/heroui-vue";
import { defineComponent } from "vue";
export default defineComponent(() => () => <DateField class="w-[256px]" name="date" render={props => <div {...props} data-custom="date-field" />}>
      <Label render={props => <span {...props} data-custom="date-field-label" />}>Date</Label>
      <DateField.Group render={props => <div {...props} data-custom="date-field-group" />}>
        <DateField.Input render={props => <div {...props} data-custom="date-field-input" />}>
          {segment => <DateField.Segment segment={segment} />}
        </DateField.Input>
      </DateField.Group>
    </DateField>);
export default CustomRenderFunction;
